parameters:
        donjohn.media.event.api_listener.class: Donjohn\MediaBundle\Event\Listener\ApiListener
services:
    Donjohn\MediaBundle\Event\Listener\ApiListener:
        class: "%donjohn.media.event.api_listener.class%"
        arguments:
            $providerFactory: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
            $classMedia: "%donjohn.media.entity%"
        tags:
            - { name: kernel.event_listener, event: kernel.view,  priority: 63 }
