services:
    Donjohn\MediaBundle\EventListener\ApiListener:
        arguments:
            $providerFactory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
        tags:
            - { name: kernel.event_listener, event: kernel.view,  priority: 63 }

    Donjohn\MediaBundle\Serializer\MediaNormalizer:
        parent: serializer.normalizer.object
        tags:
            - { name: serializer.normalizer }
