parameters:
    donjohn.media.oneup_uploader.namer.original.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer
    donjohn.media.fine_uploader.template: DonjohnMediaBundle:Form:fine_uploader_template.html.twig
    donjohn.media.fine_uploader.type.class: Donjohn\MediaBundle\Form\Type\MediaFineUploaderType


services:
    donjohn.oneup_uploader.namer.original:
        class: "%donjohn.media.oneup_uploader.namer.original.class%"

    donjohn.media.fine_uploader.type:
        class: "%donjohn.media.fine_uploader.type.class%"
        arguments: ["%donjohn.media.entity%", "@oneup_uploader.orphanage.medias", "%donjohn.media.chunk_size%"]
        tags:
            - { name: form.type }
