parameters:
    donjohn.media.uploader.naming.original_namer.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer

services:
    Donjohn\MediaBundle\Form\Type\MediaFineUploaderType:
        arguments:
            $chunkSize: "%donjohn.media.chunk_size%"
            $filesystemOrphanageStorage: "?@oneup_uploader.orphanage.medias"
            $providerFactory: "@donjohn.media.provider.factory"
        tags: [form.type]

    donjohn.media.uploader.naming.original_namer:
        class: "%donjohn.media.uploader.naming.original_namer.class%"
        public: true




