parameters:
    donjohn.media.form.media.fine_uploader.type.class: Donjohn\MediaBundle\Form\Type\MediaFineUploaderType
    donjohn.media.uploader.naming.original_namer.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Donjohn\MediaBundle\Form\Type\MediaFineUploaderType:
        class: "%donjohn.media.form.media.fine_uploader.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"
            $chunkSize: "%donjohn.media.chunk_size%"

    Donjohn\MediaBundle\Uploader\Naming\OriginalNamer:
        class: "%donjohn.media.uploader.naming.original_namer.class%"
        public: true

    donjohn.oneup_uploader.namer.original: '@Donjohn\MediaBundle\Uploader\Naming\OriginalNamer'

