parameters:
    oneup_uploader.controller.fineuploader.class: Donjohn\MediaBundle\Controller\FineUploaderController
    oneup_uploader.orphanage.class: Donjohn\MediaBundle\Uploader\Storage\FilesystemOrphanageStorage

services:
    Donjohn\MediaBundle\Uploader\Naming\OriginalNamer:
        public: true

    Donjohn\MediaBundle\Routing\Loader\DonjohnMediaLoader:
        decorates: oneup_uploader.routing.loader
        arguments:
            $loader: '@Donjohn\MediaBundle\Routing\Loader\DonjohnMediaLoader.inner'
            $mappingName: "%donjohn.media.one_up.mapping_name%"




