parameters:
    donjohn.media.form.media.fine_uploader.type.class: Donjohn\MediaBundle\Form\Type\MediaFineUploaderType
    donjohn.media.uploader.naming.original_namer.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer

services:
    Donjohn\MediaBundle\Form\Type\MediaFineUploaderType:
        class: "%donjohn.media.form.media.fine_uploader.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"
            $chunkSize: "%donjohn.media.chunk_size%"
            $filesystemOrphanageStorage: "@oneup_uploader.orphanage.medias"
            $providerFactory: Donjohn\MediaBundle\Provider\Factory\ProviderFactory

    Donjohn\MediaBundle\Uploader\Naming\OriginalNamer:
        class: "%donjohn.media.uploader.naming.original_namer.class%"
        public: true

    donjohn.oneup_uploader.namer.original: '@Donjohn\MediaBundle\Uploader\Naming\OriginalNamer'

