parameters:
    donjohn.oneup_uploader.namer.original.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer

services:
    donjohn.oneup_uploader.namer.original:
        class: "%donjohn.oneup_uploader.namer.original.class%"

    donjohn.media.fine_uploader.type:
        class: "%donjohn.media.fine_uploader.type.class%"
        arguments: ["%donjohn.media.entity%", "@oneup_uploader.orphanage.medias"]
        tags:
            - { name: form.type }