parameters:
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.file.provider.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.image.provider.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.local.filesystem.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem

services:
    donjohn.media.local.filesystem:
        class: "%donjohn.media.local.filesystem.class%"
        arguments: ["%assetic.write_to%"]

    donjohn.media.provider.factory:
        class: "%donjohn.media.provider.factory.class%"

    donjohn.media.file.provider:
        class: "%donjohn.media.file.provider.class%"
        arguments: [ "@donjohn.media.local.filesystem", "%donjohn.media.upload_folder%", "%donjohn.media.file_max_size%" ]
        tags:
            - { name: media.provider, alias: file }

    donjohn.media.image.provider:
        class: "%donjohn.media.image.provider.class%"
        parent: donjohn.media.file.provider
        calls:
            - [setCacheManager, ["@liip_imagine.cache.manager"]]
            - [setFilterConfiguration, ["@liip_imagine.filter.configuration"]]
        tags:
            - { name: media.provider, alias: image }
