parameters:
    donjohn.media.event.subscriber.class: Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.provider.file.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.provider.image.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.form.media.collection.type.class: Donjohn\MediaBundle\Form\Type\MediaCollectionType
    donjohn.media.form.media.fine_uploader.type.class: Donjohn\MediaBundle\Form\Type\MediaFineUploaderType
    donjohn.media.form.media.gallery.type.class: Donjohn\MediaBundle\Form\Type\MediaGalleryType
    donjohn.media.form.media.type.class: Donjohn\MediaBundle\Form\Type\MediaType
    donjohn.media.filesystem.media.locale.filesystem.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
    donjohn.media.twig.extension.media.class: Donjohn\MediaBundle\Twig\Extension\MediaExtension
    donjohn.media.uploader.naming.original_namer.class: Donjohn\MediaBundle\Uploader\Naming\OriginalNamer


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber:
        class: "%donjohn.media.event.subscriber.class%"
        tags:
            - { name: doctrine.event_subscriber }


    Donjohn\MediaBundle\Provider\Factory\ProviderFactory:
        class: "%donjohn.media.provider.factory.class%"
        arguments:
            $config: "%donjohn.media.providers.config%"

    Donjohn\MediaBundle\Provider\FileProvider:
        class: "%donjohn.media.provider.file.class%"
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    Donjohn\MediaBundle\Provider\ImageProvider:
        class: "%donjohn.media.provider.image.class%"
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    _instanceof:
        Donjohn\MediaBundle\Provider\ProviderInterface:
            tags:
                - { name: media.provider }

    Donjohn\MediaBundle\Form\Type\MediaCollectionType:
        class: "%donjohn.media.form.media.collection.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Form\Type\MediaFineUploaderType:
        class: "%donjohn.media.form.media.fine_uploader.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"
            $chunkSize: "%donjohn.media.chunk_size%"

    Donjohn\MediaBundle\Form\Type\MediaGalleryType:
        class: "%donjohn.media.form.media.gallery.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Form\Type\MediaType:
        class: "%donjohn.media.form.media.type.class%"
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem:
        class: "%donjohn.media.filesystem.media.locale.filesystem.class%"
        arguments:
            $webFolder: "%assetic.write_to%"

    twig.extension.text:
       class: Twig_Extensions_Extension_Text

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl

    Donjohn\MediaBundle\Twig\Extension\MediaExtension:
        class: "%donjohn.media.twig.extension.media.class%"

    Donjohn\MediaBundle\Uploader\Naming\OriginalNamer:
        class: "%donjohn.media.uploader.naming.original_namer.class%"

    donjohn.media.type: '@Donjohn\MediaBundle\Form\Type\MediaType'
    donjohn.media_collection.type: '@Donjohn\MediaBundle\Form\Type\MediaCollectionType'
    donjohn.media_gallery.type: '@Donjohn\MediaBundle\Form\Type\MediaGalleryType'
    donjohn.media.subscriber: '@Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber'
    donjohn.oneup_uploader.namer.original: '@Donjohn\MediaBundle\Uploader\Naming\OriginalNamer'
    donjohn.media.fine_uploader.type: '@Donjohn\MediaBundle\Form\Type\MediaFineUploaderType'
    donjohn.media.local.filesystem: '@Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem'
    donjohn.media.provider.factory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
    donjohn.media.file.provider: '@Donjohn\MediaBundle\Provider\FileProvider'
    donjohn.media.image.provider: '@Donjohn\MediaBundle\Provider\ImageProvider'
    donjohn.media.twig.extension: '@Donjohn\MediaBundle\Twig\Extension\MediaExtension'