services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Donjohn\MediaBundle\:
        resource: '%kernel.root_dir%/../src/Donjohn/MediaBundle/*'
        exclude: '%kernel.root_dir%/../src/Donjohn/MediaBundle/{Controller,Model,DependencyInjection}'

    Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    _instanceof:
        Donjohn\MediaBundle\Provider\ProviderInterface:
            tags:
                - { name: media.provider }

    Donjohn\MediaBundle\Provider\Factory\ProviderFactory:
        arguments:
            $templates: "%donjohn.media.providers.templates%"

    Donjohn\MediaBundle\Provider\FileProvider:
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    Donjohn\MediaBundle\Provider\ImageProvider:
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    Donjohn\MediaBundle\Form\Type\:
        resource: '%kernel.root_dir%/../src/Donjohn/MediaBundle/Form/Type/*'
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Form\Type\MediaFineUploaderType:
        arguments:
            $classMedia: "%donjohn.media.entity%"
            $chunkSize: "%donjohn.media.chunk_size%"

    Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem:
        arguments:
            $webFolder: "%assetic.write_to%"

    Twig_Extensions_Extension_Text:
       class: Twig_Extensions_Extension_Text

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl

    Donjohn\MediaBundle\Uploader\Naming\OriginalNamer:
        public: true