parameters:
    donjohn.media.event.media_subscriber.class: Donjohn\MediaBundle\EventListener\MediaSubscriber
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.provider.file.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.provider.image.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.filesystem.media.locale.filesystem.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
    donjohn.media.twig.extension.media.class: Donjohn\MediaBundle\Twig\Extension\MediaExtension


services:
    donjohn.media.subscriber:
        class: "%donjohn.media.event.media_subscriber.class%"
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
        tags:
            - { name: doctrine.event_subscriber }


    donjohn.media.provider.factory:
        class: "%donjohn.media.provider.factory.class%"
        arguments:
            $config: "%donjohn.media.providers.config%"

    donjohn.media.file.provider:
        class: "%donjohn.media.provider.file.class%"
        arguments:
            $filesystem: "@donjohn.media.local.filesystem"
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"
        tags: [media.provider]

    donjohn.media.image.provider:
        class: "%donjohn.media.provider.image.class%"
        parent: donjohn.media.file.provider
        calls:
            - [setFilterConfiguration, ["@liip_imagine.filter.configuration"] ]
        tags: [media.provider]

    Donjohn\MediaBundle\Form\Type\MediaType:
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
        tags: [form.type]

    donjohn.media.local.filesystem:
        class: "%donjohn.media.filesystem.media.locale.filesystem.class%"
        arguments:
            $webFolder: "%kernel.project_dir%/public"

    donjohn.media.twig.extension:
        class: "%donjohn.media.twig.extension.media.class%"
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
