parameters:
    donjohn.media.event.media_subscriber.class: Donjohn\MediaBundle\EventListener\MediaSubscriber
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.provider.file.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.provider.image.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.filesystem.locale.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
    donjohn.media.twig.extension.class: Donjohn\MediaBundle\Twig\Extension\MediaExtension


services:
    donjohn.media.event.media_subscriber:
        class: "%donjohn.media.event.media_subscriber.class%"
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
        tags: [doctrine.event_subscriber]

    donjohn.media.provider.factory:
        class: "%donjohn.media.provider.factory.class%"
        arguments:
            $config: "%donjohn.media.providers.config%"

    donjohn.media.provider.file:
        class: "%donjohn.media.provider.file.class%"
        arguments:
            $filesystem: "@donjohn.media.filesystem.local"
            $fileMaxSize: "%donjohn.media.file_max_size%"
        calls:
            - [setMediaFilesystem, ["@donjohn.media.filesystem.local"]]
        tags: [media.provider]

    donjohn.media.provider.image:
        class: "%donjohn.media.provider.image.class%"
        parent: donjohn.media.provider.file
        tags: [media.provider]

    Donjohn\MediaBundle\Form\Type\MediaType:
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
        tags: [form.type]

    donjohn.media.filesystem.local:
        class: "%donjohn.media.filesystem.locale.class%"
        arguments:
            $requestStack: "@request_stack"
            $rootFolder: "%kernel.project_dir%/web"
            $uploadFolder: "%donjohn.media.upload_folder%"

    donjohn.media.twig.extension:
        class: "%donjohn.media.twig.extension.class%"
        arguments:
            $providerFactory: "@donjohn.media.provider.factory"
        tags: [twig.extension]
