services:
    Donjohn\MediaBundle\EventListener\MediaSubscriber:
        arguments:
            $providerFactory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
        tags: [doctrine.event_subscriber]

    Donjohn\MediaBundle\Provider\Factory\ProviderFactory:
        arguments: ~

    Donjohn\MediaBundle\Provider\FileProvider:
        arguments:
            $filesystem: '@Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem'
            $fileMaxSize: "%donjohn.media.file_max_size%"
        calls:
            - [setMediaFilesystem, ['@Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem']]
        tags: [media.provider]

    Donjohn\MediaBundle\Provider\ImageProvider:
        parent: Donjohn\MediaBundle\Provider\FileProvider
        tags: [media.provider]

    Donjohn\MediaBundle\Form\Type\MediaType:
        arguments:
            $providerFactory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
            $fineUploaderTemplate: "%donjohn.media.fine_uploader.template%"
            $oneupMappingName: "%donjohn.media.one_up.mapping_name%"
            $filesystemOrphanageStorage: ~
        tags: [form.type]

    Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem:
        arguments:
            $requestContext: "@router.request_context"
            $rootFolder: "%donjohn.media.root_folder%"
            $uploadFolder: "%donjohn.media.upload_folder%"

    Donjohn\MediaBundle\Twig\Extension\MediaExtension:
        arguments:
            $providerFactory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
            $normalizer: '@serializer.normalizer.object'
        tags: [twig.extension]
