parameters:
    donjohn.media.event.media_subscriber.class: Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.provider.file.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.provider.image.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.filesystem.media.locale.filesystem.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
    donjohn.media.twig.extension.media.class: Donjohn\MediaBundle\Twig\Extension\MediaExtension


services:
    Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber:
        class: "%donjohn.media.event.media_subscriber.class%"
        alias: donjohn.media.subscriber
        arguments:
            $providerFactory: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
        tags:
            - { name: doctrine.event_subscriber }


    Donjohn\MediaBundle\Provider\Factory\ProviderFactory:
        class: "%donjohn.media.provider.factory.class%"
        alias: donjohn.media.provider.factory
        arguments:
            $config: "%donjohn.media.providers.config%"

    Donjohn\MediaBundle\Provider\FileProvider:
        class: "%donjohn.media.provider.file.class%"
        alias: donjohn.media.file.provider
        arguments:
            $filesystem: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    Donjohn\MediaBundle\Provider\ImageProvider:
        class: "%donjohn.media.provider.image.class%"
        alias: donjohn.media.image.provider
        parent: Donjohn\MediaBundle\Provider\FileProvider
        calls:
            - [setFilterConfiguration, ["@liip_imagine.filter.configuration"] ]

    Donjohn\MediaBundle\Form\Type\MediaCollectionType:
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Form\Type\MediaGalleryType:
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Form\Type\MediaType:
        arguments:
            $providerFactory: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem:
        class: "%donjohn.media.filesystem.media.locale.filesystem.class%"
        alias: donjohn.media.local.filesystem
        arguments:
            $webFolder: "%kernel.project_dir%/public"

    Donjohn\MediaBundle\Twig\Extension\MediaExtension:
        class: "%donjohn.media.twig.extension.media.class%"
        alias: donjohn.media.twig.extension
        arguments:
            $providerFactory: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
            $twig: \Twig_Environment
            $router: "@router"
