parameters:
    donjohn.media.event.media_subscriber.class: Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber
    donjohn.media.provider.factory.class: Donjohn\MediaBundle\Provider\Factory\ProviderFactory
    donjohn.media.provider.file.class: Donjohn\MediaBundle\Provider\FileProvider
    donjohn.media.provider.image.class: Donjohn\MediaBundle\Provider\ImageProvider
    donjohn.media.filesystem.media.locale.filesystem.class: Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem
    donjohn.media.twig.extension.media.class: Donjohn\MediaBundle\Twig\Extension\MediaExtension


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Donjohn\MediaBundle\:
        resource: '../../*'
        exclude: '../../{Controller,Model,DependencyInjection,Event/Listener,Form/Transformer,Form/Type/MediaFineUploaderType*,Provider/Guesser,Twig/Node,Twig/TokenParser,Uploader}'

    Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber:
        class: "%donjohn.media.event.media_subscriber.class%"
        tags:
            - { name: doctrine.event_subscriber }


    Donjohn\MediaBundle\Provider\Factory\ProviderFactory:
        class: "%donjohn.media.provider.factory.class%"
        arguments:
            $config: "%donjohn.media.providers.config%"

    Donjohn\MediaBundle\Provider\FileProvider:
        class: "%donjohn.media.provider.file.class%"
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"

    Donjohn\MediaBundle\Provider\ImageProvider:
        class: "%donjohn.media.provider.image.class%"
        arguments:
            $uploadFolder: "%donjohn.media.upload_folder%"
            $fileMaxSize: "%donjohn.media.file_max_size%"
        calls:
            - [setFilterConfiguration, "@liip_imagine.filter.configuration"]

    Donjohn\MediaBundle\Form\Type\:
        resource: '../../Form/Type/*'
        exclude: '../../Form/Type/MediaFineUploaderType*'
        arguments:
            $classMedia: "%donjohn.media.entity%"

    Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem:
        class: "%donjohn.media.filesystem.media.locale.filesystem.class%"
        arguments:
            $webFolder: "%kernel.project_dir%/public"

    twig.extension.text:
       class: Twig_Extensions_Extension_Text

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl

    Donjohn\MediaBundle\Twig\Extension\MediaExtension:
        class: "%donjohn.media.twig.extension.media.class%"


    donjohn.media.subscriber: '@Donjohn\MediaBundle\Event\Subscriber\MediaSubscriber'
    donjohn.media.local.filesystem: '@Donjohn\MediaBundle\Filesystem\MediaLocalFilesystem'
    donjohn.media.provider.factory: '@Donjohn\MediaBundle\Provider\Factory\ProviderFactory'
    donjohn.media.file.provider: '@Donjohn\MediaBundle\Provider\FileProvider'
    donjohn.media.image.provider: '@Donjohn\MediaBundle\Provider\ImageProvider'
    donjohn.media.twig.extension: '@Donjohn\MediaBundle\Twig\Extension\MediaExtension'
